'use strict';

nbe.state.line_classes = [
	'center',
	'right',
	'justify',
	'heading1',
	'heading2',
	'heading3',
	'heading4',
	'heading5',
	'heading6',
	'disc',
	'lower-alpha',
	'lower-roman',
	'square',
	'upper-alpha',
	'upper-roman',
	'ordered',
	'line_spacing_05',
	'line_spacing_06',
	'line_spacing_07',
	'line_spacing_08',
	'line_spacing_09',
	'line_spacing_10',
	'line_spacing_11',
	'line_spacing_12',
	'line_spacing_13',
	'line_spacing_14',
	'line_spacing_15',
	'line_spacing_16',
	'line_spacing_17',
	'line_spacing_18',
	'line_spacing_19',
	'line_spacing_20'
];
